INSERT INTO VAT_CATEGORY(CREATED_BY,CREATED_DATE,DEFAULT_FLAG,NAME,ORDER_SEQUENCE,VAT) VALUES(1,NOW(),'Y','Zero',1,0);
INSERT INTO VAT_CATEGORY(CREATED_BY,CREATED_DATE,DEFAULT_FLAG,NAME,ORDER_SEQUENCE,VAT) VALUES(1,NOW(),'N','5%',2,5);

INSERT INTO PATCH(EXECUTION_DATE,PATCH_NO) VALUES(NOW(),'20180119');