CREATE VIEW CONTACTVIEW AS
SELECT c.CONTACT_ID ,c.CONTACT_TYPE,c.EMAIL,c.FIRST_NAME,c.MIDDLE_NAME,c.LAST_NAME,c.ORGANIZATION,
(select cr.CURRENCY_SYMBOL AS CURRENCY_SYMBOL from currency cr where c.CURRENCY_CODE = cr.CURRENCY_CODE) AS CURRENCY_SYMBOL,
(select t.TITLE_DESCRIPTION AS NEXT_DUE_DATE from title t where c.TITLE_CODE = t.TITLE_CODE) AS TITLE,
c.TELEPHONE, 
(SELECT i.INVOICE_DUE_DATE AS NEXT_DUE_DATE FROM invoice AS i WHERE c.CONTACT_ID = i.CONTACT_ID AND i.DUE_AMOUNT != 0 ORDER BY i.INVOICE_DUE_DATE LIMIT 0,1) AS NEXT_DUE_DATE ,
(SELECT i.DUE_AMOUNT AS DUE_AMOUNT FROM invoice AS I WHERE c.CONTACT_ID = i.CONTACT_ID AND i.DUE_AMOUNT != 0 ORDER BY i.INVOICE_DUE_DATE LIMIT 0,1) AS DUE_AMOUNT 
FROM CONTACT AS C WHERE c.CONTACT_TYPE = 2 AND c.DELETE_FLAG !=1
UNION
SELECT c.CONTACT_ID ,c.CONTACT_TYPE,c.EMAIL,c.FIRST_NAME,c.MIDDLE_NAME,c.LAST_NAME,c.ORGANIZATION,
(select cr.CURRENCY_SYMBOL AS CURRENCY_SYMBOL from currency cr where c.CURRENCY_CODE = cr.CURRENCY_CODE) AS CURRENCY_SYMBOL,
(select t.TITLE_DESCRIPTION AS NEXT_DUE_DATE from title t where c.TITLE_CODE = t.TITLE_CODE) AS TITLE,
c.TELEPHONE, 
(SELECT p.PURCHASE_DUE_DATE AS NEXT_DUE_DATE FROM purchase AS p WHERE c.CONTACT_ID = p.CONTACT_ID AND p.PURCHASE_DUE_AMOUNT != 0 ORDER BY p.PURCHASE_DUE_DATE LIMIT 0,1) AS NEXT_DUE_DATE ,
(SELECT p.PURCHASE_DUE_AMOUNT AS DUE_AMOUNT FROM purchase AS p WHERE c.CONTACT_ID = p.CONTACT_ID AND p.PURCHASE_DUE_AMOUNT != 0 ORDER BY p.PURCHASE_DUE_DATE LIMIT 0,1) AS DUE_AMOUNT 
FROM CONTACT AS C WHERE c.CONTACT_TYPE = 1 AND c.DELETE_FLAG !=1
UNION
SELECT c.CONTACT_ID ,c.CONTACT_TYPE,c.EMAIL,c.FIRST_NAME,c.MIDDLE_NAME,c.LAST_NAME,c.ORGANIZATION,
(select cr.CURRENCY_SYMBOL AS CURRENCY_SYMBOL from currency cr where c.CURRENCY_CODE = cr.CURRENCY_CODE) AS CURRENCY_SYMBOL,
(select t.TITLE_DESCRIPTION AS NEXT_DUE_DATE from title t where c.TITLE_CODE = t.TITLE_CODE) AS TITLE,
c.TELEPHONE,NULL,NULL 
FROM CONTACT AS C WHERE c.CONTACT_TYPE = 3 AND c.DELETE_FLAG !=1
UNION
SELECT c.CONTACT_ID,c.CONTACT_TYPE,c.EMAIL,c.FIRST_NAME,c.MIDDLE_NAME,c.LAST_NAME,c.ORGANIZATION,
(select cr.CURRENCY_SYMBOL AS CURRENCY_SYMBOL from currency cr where c.CURRENCY_CODE = cr.CURRENCY_CODE) AS CURRENCY_SYMBOL,
(select t.TITLE_DESCRIPTION AS NEXT_DUE_DATE from title t where c.TITLE_CODE = t.TITLE_CODE) AS TITLE,
c.TELEPHONE,NULL,NULL FROM CONTACT AS C WHERE c.CONTACT_ID NOT IN 
(SELECT 
(SELECT c.CONTACT_ID AS NEXT_DUE_DATE FROM invoice AS I WHERE c.CONTACT_ID = i.CONTACT_ID AND i.DUE_AMOUNT != 0 ORDER BY i.INVOICE_DUE_DATE LIMIT 0,1) AS CONTACT_ID
FROM contact AS c WHERE c.CONTACT_TYPE = 2 AND c.DELETE_FLAG !=1 ) 
AND c.CONTACT_ID NOT IN 
(SELECT 
(SELECT p.CONTACT_ID AS NEXT_DUE_DATE FROM purchase AS p WHERE c.CONTACT_ID = p.CONTACT_ID AND p.PURCHASE_DUE_AMOUNT != 0 ORDER BY p.PURCHASE_DUE_DATE LIMIT 0,1) AS CONTACT_ID 
FROM contact AS c WHERE c.CONTACT_TYPE = 1 AND c.DELETE_FLAG !=1)
AND c.CONTACT_ID NOT IN 
(SELECT c.CONTACT_ID FROM contact AS c WHERE c.CONTACT_TYPE = 3 AND c.DELETE_FLAG !=1) AND c.DELETE_FLAG !=1


