INSERT INTO vat_category(CREATED_BY,CREATED_DATE,DEFAULT_FLAG,NAME,ORDER_SEQUENCE,VAT) VALUES(1,now(),'Y','Zero',1,0);
INSERT INTO vat_category(CREATED_BY,CREATED_DATE,DEFAULT_FLAG,NAME,ORDER_SEQUENCE,VAT) VALUES(1,now(),'N','5%',2,5);

INSERT INTO PATCH(EXECUTION_DATE,PATCH_NO) VALUES(NOW(),'01192018');