UPDATE `BANK_ACCOUNT_TYPE` SET `NAME` = 'Saving' WHERE `ID` = 1;
UPDATE `BANK_ACCOUNT_TYPE` SET `NAME` = 'Current' WHERE `ID` = 2;
INSERT INTO PATCH(EXECUTION_DATE,PATCH_NO) VALUES(NOW(),'20180227');