ALTER TABLE `BANK_FEED_STATUS` CHANGE `ORDER_SEQUENCE` `ORDER_SEQUENCE` INT(11) NULL ;
ALTER TABLE `BANK_ACCOUNT_STATUS` CHANGE `ORDER_SEQUENCE` `ORDER_SEQUENCE` INT(11) NULL ;
ALTER TABLE `BANK_ACCOUNT_TYPE` CHANGE `ORDER_SEQUENCE` `ORDER_SEQUENCE` INT(11) NULL ;
ALTER TABLE `BANK_FEED_STATUS` CHANGE `ORDER_SEQUENCE` `ORDER_SEQUENCE` INT(11) NULL ;
ALTER TABLE `COMPANY_TYPE` CHANGE `ORDER_SEQUENCE` `ORDER_SEQUENCE` INT(11) NULL ;
ALTER TABLE `COUNTRY` CHANGE `ORDER_SEQUENCE` `ORDER_SEQUENCE` INT(11) NULL ;
ALTER TABLE `CURRENCY` CHANGE `ORDER_SEQUENCE` `ORDER_SEQUENCE` INT(11) NULL ;
ALTER TABLE `DISCOUNT_TYPE` CHANGE `ORDER_SEQUENCE` `ORDER_SEQUENCE` INT(11) NULL ;
ALTER TABLE `INDUSTRY_TYPE` CHANGE `ORDER_SEQUENCE` `ORDER_SEQUENCE` INT(11) NULL ;
ALTER TABLE `LANGUAGE` CHANGE `ORDER_SEQUENCE` `ORDER_SEQUENCE` INT(11) NULL ;
ALTER TABLE `ROLE` CHANGE `ORDER_SEQUENCE` `ORDER_SEQUENCE` INT(11) NULL ;
ALTER TABLE `TRANSACTION_TYPE` CHANGE `ORDER_SEQUENCE` `ORDER_SEQUENCE` INT(11) NULL ;

UPDATE `BANK_FEED_STATUS` SET ORDER_SEQUENCE=NULL;
UPDATE `BANK_ACCOUNT_STATUS` SET ORDER_SEQUENCE=NULL;
UPDATE `BANK_ACCOUNT_TYPE` SET ORDER_SEQUENCE=NULL;
UPDATE `BANK_FEED_STATUS` SET ORDER_SEQUENCE=NULL;
UPDATE `COMPANY_TYPE` SET ORDER_SEQUENCE=NULL;
UPDATE `COUNTRY` SET ORDER_SEQUENCE=NULL;
UPDATE `CURRENCY` SET ORDER_SEQUENCE=NULL;
UPDATE `DISCOUNT_TYPE` SET ORDER_SEQUENCE=NULL;
UPDATE `INDUSTRY_TYPE` SET ORDER_SEQUENCE=NULL;
UPDATE `LANGUAGE` SET ORDER_SEQUENCE=NULL;
UPDATE `ROLE` SET ORDER_SEQUENCE=NULL;
UPDATE `TRANSACTION_TYPE` SET ORDER_SEQUENCE=NULL;
INSERT INTO PATCH(EXECUTION_DATE,PATCH_NO) VALUES(NOW(),'20180224');






