ALTER TABLE `bank_feed_status` CHANGE `ORDER_SEQUENCE` `ORDER_SEQUENCE` INT(11) NULL ;
ALTER TABLE `bank_account_status` CHANGE `ORDER_SEQUENCE` `ORDER_SEQUENCE` INT(11) NULL ;
ALTER TABLE `bank_account_type` CHANGE `ORDER_SEQUENCE` `ORDER_SEQUENCE` INT(11) NULL ;
ALTER TABLE `bank_feed_status` CHANGE `ORDER_SEQUENCE` `ORDER_SEQUENCE` INT(11) NULL ;
ALTER TABLE `company_type` CHANGE `ORDER_SEQUENCE` `ORDER_SEQUENCE` INT(11) NULL ;
ALTER TABLE `country` CHANGE `ORDER_SEQUENCE` `ORDER_SEQUENCE` INT(11) NULL ;
ALTER TABLE `currency` CHANGE `ORDER_SEQUENCE` `ORDER_SEQUENCE` INT(11) NULL ;
ALTER TABLE `discount_type` CHANGE `ORDER_SEQUENCE` `ORDER_SEQUENCE` INT(11) NULL ;
ALTER TABLE `industry_type` CHANGE `ORDER_SEQUENCE` `ORDER_SEQUENCE` INT(11) NULL ;
ALTER TABLE `language` CHANGE `ORDER_SEQUENCE` `ORDER_SEQUENCE` INT(11) NULL ;
ALTER TABLE `role` CHANGE `ORDER_SEQUENCE` `ORDER_SEQUENCE` INT(11) NULL ;
ALTER TABLE `transaction_type` CHANGE `ORDER_SEQUENCE` `ORDER_SEQUENCE` INT(11) NULL ;

UPDATE `bank_feed_status` SET ORDER_SEQUENCE=NULL;
UPDATE `bank_account_status` SET ORDER_SEQUENCE=NULL;
UPDATE `bank_account_type` SET ORDER_SEQUENCE=NULL;
UPDATE `bank_feed_status` SET ORDER_SEQUENCE=NULL;
UPDATE `company_type` SET ORDER_SEQUENCE=NULL;
UPDATE `country` SET ORDER_SEQUENCE=NULL;
UPDATE `currency` SET ORDER_SEQUENCE=NULL;
UPDATE `discount_type` SET ORDER_SEQUENCE=NULL;
UPDATE `industry_type` SET ORDER_SEQUENCE=NULL;
UPDATE `language` SET ORDER_SEQUENCE=NULL;
UPDATE `role` SET ORDER_SEQUENCE=NULL;
UPDATE `transaction_type` SET ORDER_SEQUENCE=NULL;
INSERT INTO PATCH(EXECUTION_DATE,PATCH_NO) VALUES(NOW(),'20180224');






