UPDATE `DISCOUNT_TYPE` SET `DISCOUNT_TYPE_DESCRIPTION` = 'Percentage', `DISCOUNT_TYPE_NAME` = 'Percentage' WHERE `DISCOUNT_TYPE_CODE` = 1;
UPDATE `DISCOUNT_TYPE` SET `DELETE_FLAG` = b'1' WHERE `DISCOUNT_TYPE_CODE` = 2;

INSERT INTO PATCH(EXECUTION_DATE,PATCH_NO) VALUES(NOW(),'01252018');