UPDATE `DISCOUNT_TYPE` SET `DISCOUNT_TYPE_DESCRIPTION` = 'Percentage Discount', `DISCOUNT_TYPE_NAME` = 'Percentage Discount' WHERE `DISCOUNT_TYPE_CODE` = 1;
UPDATE `DISCOUNT_TYPE` SET `DISCOUNT_TYPE_DESCRIPTION` = 'Fixed Discount', `DISCOUNT_TYPE_NAME` = 'Fixed Discount', `DELETE_FLAG` = b'0' WHERE `DISCOUNT_TYPE_CODE` = 2;

INSERT INTO PATCH(EXECUTION_DATE,PATCH_NO) VALUES(NOW(),'20180129');