INSERT INTO CURRENCY VALUES (1,'Afghani','Afghanistan Afghani','AFN','؋','N',2,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (2,'Algeria Dinar','Algeria Dinar','DZD','د.ج','N',3,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (3,'Argentine Peso','Argentina Peso','ARS','$','N',4,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (4,'Armenian Dram','Armenia Dram','AMD','Դ','N',5,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (5,'Aruban Florin','Aruba Guilder','AWG','ƒ','N',6,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (6,'Australian Dollar','Australia Dollar','AUD','$','N',7,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (7,'Azerbaijanian Manat','Azerbaijan New Manat','AZN','ман','N',8,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (8,'Bahamian Dollar','Bahamas Dollar','BSD','$','N',9,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (9,'Bahraini Dinar','Bahrain Dinar','BHD','د.ب','N',10,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (10,'Baht','Thailand Baht','THB','฿','N',11,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (11,'Balboa','Panama Balboa','PAB','B/.','N',12,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (12,'Barbados Dollar','Barbados Dollar','BBD','$','N',13,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (13,'Belarusian Ruble','Belarus Ruble','BYN','Br','N',14,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (14,'Belize Dollar','Belize Dollar','BZD','BZ$','N',15,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (15,'Bermudian Dollar','Bermuda Dollar','BMD','$','N',16,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (16,'Bolívar','Venezuela Bolivar','VEF','Bs','N',17,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (17,'Boliviano','Bolivia Bolíviano','BOB','$b','N',18,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (18,'Brazilian Real','Brazil Real','BRL','R$','N',19,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (19,'Brunei Dollar','Brunei Darussalam Dollar','BND','$','N',20,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (20,'Bulgarian Lev','Bulgaria Lev','BGN','лв','N',21,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (21,'Burundi Franc','Burundi Franc','BIF','Fbu','N',22,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (22,'Cabo Verde Escudo','Cape Verde Escudo','CVE','Esc','N',23,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (23,'Canadian Dollar','Canada Dollar','CAD','$','N',24,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (24,'Cayman Islands Dollar','Cayman Islands Dollar','KYD','$','N',25,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (25,'CFA Franc BCEAO','Communauté Financière Africaine (BCEAO) Franc','XOF','Fr','N',26,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (26,'CFA Franc BEAC','Communauté Financière Africaine (BEAC) CFA Franc BEAC','XAF','Fr','N',27,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (27,'CFP Franc','Comptoirs Français du Pacifique (CFP) Franc','XPF','Fr','N',28,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (28,'Chilean Peso','Chile Peso','CLP','$','N',29,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (29,'Colombian Peso','Colombia Peso','COP','$','N',30,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (30,'Comoro Franc','Comoros Franc','KMF','Fr','N',31,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (31,'Congolese Franc','Congo/Kinshasa Franc','CDF','Fr','N',32,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (32,'Convertible Mark','Bosnia and Herzegovina Convertible Marka','BAM','KM','N',33,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (33,'Cordoba Oro','Nicaragua Cordoba','NIO','C$','N',34,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (34,'Costa Rican Colon','Costa Rica Colon','CRC','₡','N',35,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (35,'Cuban Peso','Cuba Peso','CUP','₱','N',36,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (36,'Czech Koruna','Czech Republic Koruna','CZK','Kč','N',37,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (37,'Dalasi','Gambia Dalasi','GMD','D','N',38,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (38,'Danish Krone','Denmark Krone','DKK','kr','N',39,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (39,'Denar','Macedonia Denar','MKD','ден','N',40,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (40,'Djibouti Franc','Djibouti Franc','DJF','Fr','N',41,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (41,'Dobra','São Tomé and Príncipe Dobra','STD','Db','N',42,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (42,'Dominican Peso','Dominican Republic Peso','DOP','RD$','N',43,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (43,'Dong','Viet Nam Dong','VND','₫','N',44,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (44,'East Caribbean Dollar','East Caribbean Dollar','XCD','$','N',45,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (45,'Egyptian Pound','Egypt Pound','EGP','£','N',46,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (46,'El Salvador Colon','El Salvador Colon','SVC','$','N',47,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (47,'Ethiopian Birr','Ethiopia Birr','ETB','Br','N',48,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (48,'Euro','Euro Member Countries','EUR','€','N',49,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (49,'Falkland Islands Pound','Falkland Islands (Malvinas) Pound','FKP','£','N',50,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (50,'Fiji Dollar','Fiji Dollar','FJD','$','N',51,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (51,'Forint','Hungary Forint','HUF','Ft','N',52,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (52,'Ghana Cedi','Ghana Cedi','GHS','¢','N',53,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (53,'Gibraltar Pound','Gibraltar Pound','GIP','£','N',54,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (54,'Gourde','Haiti Gourde','HTG','G','N',55,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (55,'Guarani','Paraguay Guarani','PYG','Gs','N',56,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (56,'Guernsey Pound','Guernsey Pound','GGP','£','N',57,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (57,'Guinea Franc','Guinea Franc','GNF','Fr','N',58,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (58,'Guyana Dollar','Guyana Dollar','GYD','$','N',59,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (59,'Hong Kong Dollar','Hong Kong Dollar','HKD','$','N',60,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (60,'Hryvnia','Ukraine Hryvnia','UAH','₴','N',61,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (61,'Iceland Krona','Iceland Krona','ISK','kr','N',62,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (62,'Indian Rupee','India Rupee','INR','₹','N',63,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (63,'Iranian Rial','Iran Rial','IRR','﷼','N',64,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (64,'Iraqi Dinar','Iraq Dinar','IQD','د.ع','N',65,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (65,'Isle of Man Pound','Isle of Man Pound','IMP','£','N',66,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (66,'Jamaican Dollar','Jamaica Dollar','JMD','J$','N',67,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (67,'Jersey Pound','Jersey Pound','JEP','£','N',68,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (68,'Jordanian Dinar','Jordan Dinar','JOD','د.ا','N',69,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (69,'Kenyan Shilling','Kenya Shilling','KES','Sh','N',70,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (70,'Kina','Papua New Guinea Kina','PGK','K','N',71,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (71,'Kip','Laos Kip','LAK','₭','N',72,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (72,'Kuna','Croatia Kuna','HRK','kn','N',73,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (73,'Kuwaiti Dinar','Kuwait Dinar','KWD','د.ك','N',74,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (74,'Kwanza','Angola Kwanza','AOA','Kz','N',75,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (75,'Kyat','Myanmar (Burma) Kyat','MMK','K','N',76,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (76,'Lari','Georgia Lari','GEL','ლ','N',77,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (77,'Lebanese Pound','Lebanon Pound','LBP','£','N',78,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (78,'Lek','Albania Lek','ALL','Lek','N',79,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (79,'Lempira','Honduras Lempira','HNL','L','N',80,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (80,'Leone','Sierra Leone Leone','SLL','Le','N',81,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (81,'Liberian Dollar','Liberia Dollar','LRD','$','N',82,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (82,'Libyan Dinar','Libya Dinar','LYD','ل.د','N',83,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (83,'Lilangeni','Swaziland Lilangeni','SZL','L','N',84,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (84,'Loti','Lesotho Loti','LSL','L','N',85,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (85,'Luigino','Seborga Luigino','SPL','','N',86,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (86,'Malagasy Ariary','Madagascar Ariary','MGA','Ar','N',87,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (87,'Malawi Kwacha','Malawi Kwacha','MWK','MK','N',88,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (88,'Malaysian Ringgit','Malaysia Ringgit','MYR','RM','N',89,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (89,'Mauritius Rupee','Mauritius Rupee','MUR','₨','N',90,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (90,'Mexican Peso','Mexico Peso','MXN','$','N',91,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (91,'Moldovan Leu','Moldova Leu','MDL','L','N',92,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (92,'Moroccan Dirham','Morocco Dirham','MAD','د.م.','N',93,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (93,'Mozambique Metical','Mozambique Metical','MZN','MT','N',94,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (94,'Naira','Nigeria Naira','NGN','₦','N',95,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (95,'Nakfa','Eritrea Nakfa','ERN','Nfk','N',96,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (96,'Namibia Dollar','Namibia Dollar','NAD','$','N',97,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (97,'Nepalese Rupee','Nepal Rupee','NPR','₨','N',98,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (98,'Netherlands Antillean Guilder','Netherlands Antilles Guilder','ANG','ƒ','N',99,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (99,'New Israeli Sheqel','Israel Shekel','ILS','₪','N',100,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (100,'New Taiwan Dollar','Taiwan New Dollar','TWD','NT$','N',101,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (101,'New Zealand Dollar','New Zealand Dollar','NZD','$','N',102,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (102,'Ngultrum','Bhutan Ngultrum','BTN','Nu','N',103,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (103,'North Korean Won','Korea (North) Won','KPW','₩','N',104,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (104,'Norwegian Krone','Norway Krone','NOK','kr','N',105,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (105,'Ouguiya','Mauritania Ouguiya','MRO','UM','N',106,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (106,'Pa\’anga','Tonga Pa\'anga','TOP','T$','N',107,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (107,'Pakistan Rupee','Pakistan Rupee','PKR','₨','N',108,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (108,'Pataca','Macau Pataca','MOP','P','N',109,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (109,'Peso Convertible','Cuba Convertible Peso','CUC','$','N',110,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (110,'Peso Uruguayo','Uruguay Peso','UYU','$U','N',111,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (111,'Philippine Peso','Philippines Peso','PHP','₱','N',112,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (112,'Pound Sterling','United Kingdom Pound','GBP','£','N',113,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (113,'Pula','Botswana Pula','BWP','P','N',114,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (114,'Qatari Rial','Qatar Riyal','QAR','﷼','N',115,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (115,'Quetzal','Guatemala Quetzal','GTQ','Q','N',116,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (116,'Rand','South Africa Rand','ZAR','R','N',117,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (117,'Rial Omani','Oman Rial','OMR','﷼','N',118,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (118,'Riel','Cambodia Riel','KHR','៛','N',119,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (119,'Romanian Leu','Romania New Leu','RON','lei','N',120,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (120,'Rufiyaa','Maldives (Maldive Islands) Rufiyaa','MVR','ރ.','N',121,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (121,'Rupiah','Indonesia Rupiah','IDR','Rp','N',122,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (122,'Russian Ruble','Russia Ruble','RUB','₽','N',123,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (123,'Rwanda Franc','Rwanda Franc','RWF','Fr','N',124,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (124,'Saint Helena Pound','Saint Helena Pound','SHP','£','N',125,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (125,'Saudi Riyal','Saudi Arabia Riyal','SAR','﷼','N',126,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (126,'Serbian Dinar','Serbia Dinar','RSD','Дин.','N',127,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (127,'Seychelles Rupee','Seychelles Rupee','SCR','₨','N',128,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (128,'Singapore Dollar','Singapore Dollar','SGD','$','N',129,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (129,'Sol','Peru Sol','PEN','S/.','N',130,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (130,'Solomon Islands Dollar','Solomon Islands Dollar','SBD','$','N',131,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (131,'Som','Kyrgyzstan Som','KGS','лв','N',132,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (132,'Somali Shilling','Somalia Shilling','SOS','S','N',133,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (133,'Somoni','Tajikistan Somoni','TJS','ЅМ','N',134,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (134,'Sri Lanka Rupee','Sri Lanka Rupee','LKR','₨','N',135,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (135,'Sudanese Pound','Sudan Pound','SDG','£','N',136,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (136,'Surinam Dollar','Suriname Dollar','SRD','$','N',137,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (137,'Swedish Krona','Sweden Krona','SEK','kr','N',138,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (138,'Swiss Franc','Switzerland Franc','CHF','CHF','N',139,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (139,'Syrian Pound','Syria Pound','SYP','£','N',140,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (140,'Taka','Bangladesh Taka','BDT','৳','N',141,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (141,'Tala','Samoa Tala','WST','T','Y',142,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (142,'Tanzanian Shilling','Tanzania Shilling','TZS','Sh','N',143,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (143,'Tenge','Kazakhstan Tenge','KZT','лв','N',144,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (144,'Trinidad and Tobago Dollar','Trinidad and Tobago Dollar','TTD','TT$','N',145,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (145,'Tugrik','Mongolia Tughrik','MNT','₮','N',146,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (146,'Tunisian Dinar','Tunisia Dinar','TND','د.ت','N',147,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (147,'Turkish Lira','Turkey Lira','TRY','TL','N',148,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (148,'Turkmenistan New Manat','Turkmenistan Manat','TMT','m','N',149,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (149,'Tuvalu Dollar','Tuvalu Dollar','TVD','$','N',150,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (150,'UAE Dirham','United Arab Emirates Dirham','AED','د.إ','Y',151,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (151,'Uganda Shilling','Uganda Shilling','UGX','Sh','N',152,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (152,'US Dollar','United States Dollar','USD','$','N',153,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (153,'Uzbekistan Sum','Uzbekistan Som','UZS','лв','N',154,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (154,'Vatu','Vanuatu Vatu','VUV','Vt','N',155,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (155,'Won','Korea (South) Won','KRW','₩','N',156,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (156,'Yemeni Rial','Yemen Rial','YER','﷼','N',157,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (157,'Yen','Japan Yen','JPY','¥','N',158,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (158,'Yuan Renminbi','China Yuan Renminbi','CNY','¥','N',159,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (159,'Zambian Kwacha','Zambia Kwacha','ZMW','ZK','N',160,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (160,'Zimbabwe Dollar','Zimbabwe Dollar','ZWD','Z$','N',161,1,CURRENT_TIMESTAMP,null,null,0,1);
INSERT INTO CURRENCY VALUES (161,'Zloty','Poland Zloty','PLN','zł','N',162,1,CURRENT_TIMESTAMP,null,null,0,1);
