ALTER TABLE `simplevat`.`TRANSACTON`
DROP FOREIGN KEY `FK_EXPLAINATION_STATUS_CODE`;
ALTER TABLE `simplevat`.`TRANSACTON`
CHANGE COLUMN `EXPLAINATION_STATUS_CODE` `EXPLANATION_STATUS_CODE` INT(11) NOT NULL ;
ALTER TABLE `simplevat`.`TRANSACTON`
ADD CONSTRAINT `FK_EXPLAINATION_STATUS_CODE`
  FOREIGN KEY (`EXPLANATION_STATUS_CODE`)
  REFERENCES `simplevat`.`EXPLANATION_STATUS` (`EXPLANATION_STATUS_CODE`);