ALTER TABLE TITLE
ALTER COLUMN VERSION_NUMBER SET DEFAULT 1;

ALTER TABLE TITLE
ALTER COLUMN ORDER_SEQUENCE SET DEFAULT 1;

ALTER TABLE TITLE
ALTER COLUMN DELETE_FLAG SET DEFAULT 0;

ALTER TABLE TITLE
ALTER COLUMN DEFAULT_FLAG SET DEFAULT 'N';

ALTER TABLE TITLE MODIFY CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL ;