ALTER TABLE USER CHANGE COLUMN DATA_OF_BIRTH DATE_OF_BIRTH DATE NULL;

ALTER TABLE USER ADD COLUMN USER_EMAIL VARCHAR(100) NOT NULL AFTER DATE_OF_BIRTH;

CREATE UNIQUE INDEX XAK1USER ON USER
(
	USER_EMAIL ASC
);