ALTER TABLE BANK_ACCOUNT MODIFY COLUMN ISPRIMARY_ACCOUNT_FLAG TINYINT(1) NOT NULL DEFAULT '1';

ALTER TABLE BANK_ACCOUNT CHANGE COLUMN PERSONAL_CORPORATE_ACCOUNT_FLAG  PERSONAL_CORPORATE_ACCOUNT_IND CHAR(1) NOT NULL DEFAULT 'C';