ALTER TABLE `title` CHANGE `ORDER_SEQUENCE` `ORDER_SEQUENCE` INT(11) NULL;
ALTER TABLE `TRANSACTION_TYPE` CHANGE `ORDER_SEQUENCE` `ORDER_SEQUENCE` INT(11) NULL ;
UPDATE `title` SET ORDER_SEQUENCE=NULL;
UPDATE `TRANSACTION_TYPE` SET ORDER_SEQUENCE=NULL;
INSERT INTO PATCH(EXECUTION_DATE,PATCH_NO) VALUES(NOW(),'20180417');